import type { LucideIcon } from 'lucide-react';
import type { ComponentProps } from 'react';
import {
  AlertCircle,
  Armchair,
  ArrowLeft,
  BadgeCheck,
  BookOpenText,
  Brain,
  Building2,
  Check,
  CheckCircle2,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clapperboard,
  DoorOpen,
  Eye,
  FileEdit,
  Film,
  Filter,
  GitBranch,
  Globe,
  Hammer,
  Headset,
  HelpCircle,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  MonitorSmartphone,
  Paintbrush,
  Quote,
  Ratio,
  Receipt,
  RefreshCw,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Star,
  TrendingUp,
  UserPlus,
  Users,
  Video,
  Waypoints,
  X,
  Zap,
} from 'lucide-react';

/** Maps legacy Material Symbols ligature names to Lucide icons (Material webfont removed for perf). */
const ICONS: Record<string, LucideIcon> = {
  west: ArrowLeft,
  error: AlertCircle,
  check_circle: CheckCircle2,
  format_quote: Quote,
  dashboard_customize: LayoutDashboard,
  edit_note: FileEdit,
  auto_awesome: Sparkles,
  layers: Layers,
  sync: RefreshCw,
  movie: Film,
  home_repair_service: Hammer,
  chair: Armchair,
  video_settings: Video,
  grid_view: LayoutGrid,
  brush: Paintbrush,
  aspect_ratio: Ratio,
  auto_stories: BookOpenText,
  bolt: Zap,
  psychology: Brain,
  language: Globe,
  arrow_back_ios_new: ChevronLeft,
  arrow_forward_ios: ChevronRight,
  group: Users,
  star: Star,
  trending_up: TrendingUp,
  public: Globe,
  architecture: Building2,
  tune: SlidersHorizontal,
  group_add: UserPlus,
  support_agent: Headset,
  verified_user: BadgeCheck,
  receipt_long: Receipt,
  shield: Shield,
  devices: MonitorSmartphone,
  check: Check,
  close: X,
  info: Info,
  expand_more: ChevronDown,
  videocam: Video,
  visibility: Eye,
  texture: Layers,
  person_add: UserPlus,
  meeting_room: DoorOpen,
  integration_instructions: Waypoints,
  photo_filter: Filter,
  kitchen: ChefHat,
  flowsheet: GitBranch,
  movie_edit: Clapperboard,
};

type LucideIconProps = ComponentProps<typeof HelpCircle>;

export type MaterialIconProps = {
  name: string;
} & LucideIconProps;

export function MaterialIcon({ name, className, strokeWidth = 1.75, ...rest }: MaterialIconProps) {
  const Icon = ICONS[name] ?? HelpCircle;
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden {...rest} />;
}
