import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const SRC_DIR = path.join(ROOT, 'public', 'app');
const BACKUP_DIR = path.join(ROOT, 'assets-source', 'app', 'originals');
const OUT_PLACEHOLDERS = path.join(ROOT, 'src', 'data', 'imagePlaceholders.ts');

const FILES = [
  'render',
  'video',
  'visual',
  'texture',
  'human-enhancer',
  'virtual',
  'prompt',
  'photo-enhancer',
  'kitchen',
  'tool-render',
  'tool-video',
  'course-render',
  'course-video',
];

const TARGET_WIDTH = 1280;
const TARGET_QUALITY = 78;
const PLACEHOLDER_WIDTH = 24;
const PLACEHOLDER_QUALITY = 40;

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function fileExists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function findSource(name) {
  // Prefer original backup if present, else use whatever lives in public/app
  const backupPath = path.join(BACKUP_DIR, `${name}.jpeg`);
  if (await fileExists(backupPath)) return backupPath;

  const livePath = path.join(SRC_DIR, `${name}.jpeg`);
  if (await fileExists(livePath)) return livePath;

  return null;
}

async function backupIfNeeded(name) {
  const livePath = path.join(SRC_DIR, `${name}.jpeg`);
  const backupPath = path.join(BACKUP_DIR, `${name}.jpeg`);
  if ((await fileExists(livePath)) && !(await fileExists(backupPath))) {
    await fs.copyFile(livePath, backupPath);
    return true;
  }
  return false;
}

async function processOne(name) {
  await backupIfNeeded(name);
  const source = await findSource(name);
  if (!source) {
    console.warn(`[skip] no source for ${name}`);
    return null;
  }

  const buf = await fs.readFile(source);
  const image = sharp(buf, { failOnError: false });
  const meta = await image.metadata();

  const outWebp = path.join(SRC_DIR, `${name}.webp`);

  await image
    .clone()
    .resize({ width: TARGET_WIDTH, withoutEnlargement: true })
    .webp({ quality: TARGET_QUALITY, effort: 5 })
    .toFile(outWebp);

  const placeholderBuf = await image
    .clone()
    .resize({ width: PLACEHOLDER_WIDTH })
    .webp({ quality: PLACEHOLDER_QUALITY, effort: 4 })
    .toBuffer();

  const placeholder = `data:image/webp;base64,${placeholderBuf.toString('base64')}`;

  const [srcStat, webpStat] = await Promise.all([fs.stat(source), fs.stat(outWebp)]);

  return {
    name,
    sourceBytes: srcStat.size,
    webpBytes: webpStat.size,
    srcDim: `${meta.width}x${meta.height}`,
    placeholder,
  };
}

async function writePlaceholders(map) {
  const header = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit manually.\n// Run \`npm run optimize-images\` to regenerate.\n\nexport const PLACEHOLDERS: Record<string, string> = {\n`;
  const body = Object.entries(map)
    .map(([k, v]) => `  '${k}': '${v}',`)
    .join('\n');
  const footer = `\n};\n`;
  await ensureDir(path.dirname(OUT_PLACEHOLDERS));
  await fs.writeFile(OUT_PLACEHOLDERS, header + body + footer, 'utf8');
}

async function main() {
  await ensureDir(BACKUP_DIR);

  const placeholders = {};
  const results = [];
  for (const name of FILES) {
    const result = await processOne(name);
    if (result) {
      results.push(result);
      placeholders[`/app/${name}.webp`] = result.placeholder;
    }
  }

  await writePlaceholders(placeholders);

  const summary = results.map((r) => ({
    name: r.name,
    src: `${(r.sourceBytes / 1024 / 1024).toFixed(2)} MB (${r.srcDim})`,
    webp: `${(r.webpBytes / 1024).toFixed(1)} KB`,
    saving: `${(100 - (r.webpBytes / r.sourceBytes) * 100).toFixed(1)}%`,
  }));

  const totalSrc = results.reduce((s, r) => s + r.sourceBytes, 0);
  const totalOut = results.reduce((s, r) => s + r.webpBytes, 0);

  console.log(JSON.stringify(summary, null, 2));
  console.log(
    `\nTotal: ${(totalSrc / 1024 / 1024).toFixed(2)} MB → ${(totalOut / 1024 / 1024).toFixed(2)} MB` +
      ` (${(100 - (totalOut / totalSrc) * 100).toFixed(1)}% lighter)`,
  );
  console.log(`Placeholders → ${path.relative(ROOT, OUT_PLACEHOLDERS)}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
