import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home Page',
    'nav.partners': 'Partners',
    'nav.academy': 'Academy',
    'nav.workspace': 'Nbox AI App',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'footer.copyright': '© 2026 NBOX AI. ARCHITECTURAL AI ECOSYSTEM.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'home.hero.badge': 'Nbox AI Engine V3.0',
    'home.hero.title': 'NBOX AI - ARCHITECTURAL ECOSYSTEM',
    'home.hero.desc': 'A complete suite of solutions to boost your workflow performance by 5X. Reimagining spaces with high-octane neural intelligence.',
    'home.demo.title': 'DESIGN IN ACTION',
    'home.demo.desc': 'Witness the transformation. From sketch to high-fidelity cinematic render in seconds.',
    'home.founder.title': 'THE VISIONARY',
    'home.founder.name': 'TRAN MINH NHAT',
    'home.founder.story': 'The architect of Nbox AI. A pioneer in bridging advanced neural computation with architectural spatial design. Mission: Accelerating the world\'s creative output.',
    'home.founder.slogan': 'CRAFTING REALITY AT THE SPEED OF THOUGHT.',
    'home.cta.ready': 'READY TO REIMAGINE?',
    'home.cta.desc': 'Join the vanguard of the architectural revolution. Experience the speed of Nbox AI design today.',
    'home.cta.trial': 'Start Sculpting',
    'home.hero.cta.ignite': 'IGNITE ARCHITECTURE',
    'home.hero.cta.demo': 'VIEW DEMO',
    'home.stats.users': 'Active Designers',
    'home.stats.rate': 'Success Rate',
    'home.stats.support': 'Customer Support',
    'home.stats.latency': 'Inference Speed',
    'home.stack.tag': 'The Architecture Stack',
    'home.stack.title': 'DESIGN WITHOUT LIMITS',
    'home.stack.desc': 'Our ecosystem is engineered for high-velocity output, from initial sketch to final masterpiece.',
    'home.services.1.title': 'AI Photo Render',
    'home.services.1.desc': 'Create realistic 3D perspectives from 2D drawings or rough sketches.',
    'home.services.2.title': 'AI Interior Design',
    'home.services.2.desc': 'Automated suggestions for style, materials, and interior layout.',
    'home.services.3.title': 'AI House Renovation',
    'home.services.3.desc': 'Renovation suggestions for facades and interiors based on current photos.',
    'home.services.4.title': 'AI Floor Plan Render',
    'home.services.4.desc': 'Convert CAD technical drawings into intuitive 2D/3D colored floor plans.',
    'home.services.5.title': 'AI Small Landscape',
    'home.services.5.desc': 'Design gardens, small landscapes, and green spaces harmonized with the building.',
    'home.services.6.title': 'AI Urban Planning',
    'home.services.6.desc': 'Analyze and render residential and urban planning with custom density.',
    'home.services.7.title': 'AI Architecture Film',
    'home.services.7.desc': 'Create vivid 3D visualization videos from static images with smooth camera movement.',
    'home.services.8.title': 'AI Real Estate Poster',
    'home.services.8.desc': 'Design professional real estate advertising posters with AI optimization.',
    'partners.hero.tag': 'Strategic Network',
    'partners.hero.title': 'TRUSTED BY GLOBAL DESIGN FIRMS',
    'partners.hero.desc': 'Collaborating with top-tier architectural studios to deploy high-velocity AI rendering solutions globally.',
    'partners.deployed.title': 'DEPLOYED SOLUTIONS',
    'partners.deployed.desc': 'Real-world applications of Nbox AI across our global partner network.',
    'academy.hero.tag': 'NBOX DESIGN LAB V3.0',
    'academy.hero.title': 'NBOX ACADEMY - PRACTICAL AI COURSES',
    'academy.hero.desc': 'Online courses built for architects, visualizers, and real estate professionals to master practical AI applications.',
    'academy.course.link': 'COURSE LINK',
    'academy.testimonials.title': 'STUDENT VOICES ON NBOX ACADEMY',
    'academy.faq.title': 'FREQUENTLY ASKED QUESTIONS',
    'academy.detail.back': 'BACK',
    'academy.detail.courseDetails': 'COURSE DETAILS',
    'academy.detail.for': 'FOR',
    'academy.detail.goal': 'GOAL',
    'academy.detail.problems': 'CURRENT PROBLEMS',
    'academy.detail.whatIs': 'WHAT IS',
    'academy.detail.learn': 'WHAT WILL YOU LEARN?',
    'academy.detail.outcomes': 'COURSE OUTCOMES',
    'academy.detail.philosophy': 'TRAINING PHILOSOPHY',
    'academy.detail.register': 'REGISTER NOW',
    'workspace.title': 'NBOX AI APP',
    'workspace.hero.desc': 'Access specialized AI applications for modern architecture.',
    'workspace.tabs.catalog': 'AI APPS',
    'workspace.tabs.pro': 'AI FLOW TOOLS',
    'workspace.modal.link': 'Quick Access',
    'workspace.modal.video': 'Tutorial Video',
    'workspace.modal.tips': 'Usage Tips',
    'contact.hero.tag': 'Connect With Us',
    'contact.hero.title': 'JOIN THE DESIGN REVOLUTION',
    'contact.hero.desc': 'Reach out to the Nbox AI team for architectural collaboration, support, or custom enterprise solutions.',
    'contact.journey.title': 'START YOUR JOURNEY',
    'contact.network.title': 'DIRECT CONNECTION',
    'contact.lab.title': 'JOIN NBOX AI LAB',
    'contact.lab.desc': 'Be part of the future of architecture. We are always looking for passionate architects and AI researchers.',
    'contact.lab.cta': 'Join the Lab',
    'contact.social.title': 'SOCIAL ECOSYSTEM',
    'home.founder_bio.title': 'Who is Tran Minh Nhat?',
    'home.demo.secrets': 'AI ARCHITECT SECRETS',
    'home.demo.action': 'DESIGN IN ACTION',
    'home.demo.tagline': 'Accelerating design boundaries with the power of artificial intelligence.',
    'home.demo.try': 'TRY NOW',
    'academy.available': 'AVAILABLE COURSES',
    'academy.training': 'TRAINING SYSTEM',
    'services.title': 'AI ARCHITECTURE & REAL ESTATE SERVICES',
    'services.desc': 'Providing specialized AI services, helping individuals and businesses create images, improve renders and produce project videos quickly and with high quality.',
    'services.render.title': '1. AI Render Service',
    'services.render.subtitle': 'With just a hand sketch or initial idea, NBOX AI helps you create visual perspectives quickly.',
    'services.render.f1': 'Customize by style, color tone and design concept',
    'services.render.f2': 'Flexible with many architectural styles',
    'services.render.f3': 'Available in a few hours',
    'services.render.f4': 'Realistic image quality, lighting and natural materials',
    'services.improve.title': '2. Render Improvement Service',
    'services.improve.subtitle': 'AI application combined with intensive processing helps images become clear, balanced in light and more realistic while still keeping the original design idea.',
    'services.improve.f1': 'Upgrade images to high resolution (4K Ultra HD)',
    'services.improve.f2': 'Balance lighting, improve materials, increase realism',
    'services.improve.f3': 'Ensures 90% of the original design idea is kept',
    'services.improve.f4': 'Fast processing, suitable for both individual and business projects',
    'services.video.title': '3. AI Architectural - Real Estate Filmmaking Service',
    'services.video.subtitle': 'An effective solution for presenting, pitching projects and real estate marketing, helping customers and investors easily visualize and make decisions.',
    'services.video.f1': 'Convert render images into smooth motion videos',
    'services.video.f2': 'Increase visibility and emotion when presenting projects',
    'services.video.f3': 'Easy to customize according to content requirements and purpose of use',
    'services.details.btn': 'VIEW DETAILS',
    'services.details.title': 'DETAILED INFORMATION',
    'services.details.render.req.title': 'Customer provides:',
    'services.details.render.req.1': 'Improvement and editing requirements.',
    'services.details.render.req.2': 'Highest resolution possible images.',
    'services.details.render.edit.title': 'Revision Policy:',
    'services.details.render.edit.1': 'Free small revisions.',
    'services.details.render.edit.2': 'Major revisions or re-renders: 75% fee.',
    'services.details.render.price.1': 'Small project (Townhouse, villa)',
    'services.details.render.price.1.val': '200k/image',
    'services.details.render.price.2': 'Large project (Hotel, restaurant, apartment)',
    'services.details.render.price.2.val': '400k/image',
    'services.details.render.price.3': 'Real Estate Project',
    'services.details.render.price.3.val': '500k - 1m/image',
    'services.details.video.price.1': 'Small project video (1 min)',
    'services.details.video.price.1.val': '1.5m / video',
    'services.details.video.price.2': 'Large project video (1 min)',
    'services.details.video.price.2.val': '2.5m / video',
    'services.details.video.price.3': 'RE Project video (1 min)',
    'services.details.video.price.3.val': '3.5m / video',
    'services.details.video.req.title': 'Customer provides:',
    'services.details.video.req.1': 'Script.',
    'services.details.video.req.2': 'Architectural images.',
    'services.details.video.req.3': 'Other requirements (text, voiceover, effects...).',
    'academy.cta.master': 'READY TO MASTER TOP-TIER AI?',
    'course.render.details': 'DETAILED INFORMATION',
    'academy.card.tools': 'TOOLS',
    'academy.card.format': 'FORMAT',
    'academy.card.content': 'CONTENT',
    'partners.custom_app.title': 'WHO IS THE CUSTOM BUSINESS APP PACKAGE FOR?',
    'partners.custom_app.card1.title': 'Catch the Trend',
    'partners.custom_app.card1.desc': 'Businesses wanting to apply AI technology to their workflow',
    'partners.custom_app.card2.title': 'Increase Productivity',
    'partners.custom_app.card2.desc': 'Businesses wanting to optimize performance and reduce render time',
    'partners.custom_app.card3.title': 'Distinct Web Interface',
    'partners.custom_app.card3.desc': 'Businesses wanting to show professionalism and social network presence',
    'partners.benefits.title': 'BUSINESS APP PACKAGE BENEFITS',
    'partners.benefit1': 'Interface customized for each company',
    'partners.benefit2': 'Features set up based on usage needs',
    'partners.benefit3': 'Allow multiple employees to access simultaneously',
    'partners.benefit4': 'Private support group, fast response',
    'partners.benefit5': 'Update and warranty for 10 years',
    'partners.benefit6': 'Full VAT invoice support',
    'partners.pricing.title': 'PRICING PER APP',
    'partners.pricing.subtitle': '(One-time fee - Lifetime)',
    'partners.pricing.credits': 'Credits',
    'partners.pricing.choose': 'Choose this plan',
    'partners.pricing.pro_badge': 'Most Popular',
    'partners.pricing.basic': 'Basic',
    'partners.pricing.standard_pkg': 'Standard',
    'partners.pricing.business': 'Business',
    'partners.pricing.enterprise': 'Enterprise',
    'partners.pricing.private': 'Private Plan',
    'partners.pricing.devices.basic': '1–6 devices',
    'partners.pricing.devices.standard': '7–11 devices',
    'partners.pricing.devices.business': '12–16 devices',
    'partners.pricing.devices.enterprise': '17–24 devices',
    'partners.pricing.devices.private': '25+ devices',
    'partners.pricing.negotiable': 'Negotiate',
    'partners.pricing.feature.speed': 'Standard render speed',
    'partners.pricing.feature.support': '24/7 Priority support',
    'partners.pricing.feature.early_access': 'Early access features',
    'partners.pricing.ai_service.title': 'AI SERVICE',
    'partners.pricing.ai_service.subtitle': 'ARCHITECTURAL & REAL ESTATE AI SERVICES',
    'partners.pricing.ai_service.desc': 'Providing specialized AI services, helping individuals and businesses create images, improve renders, and produce project videos quickly and with high quality.',
    'partners.pricing.note': 'Price does not include 8% VAT and gateway key purchase fee',
  },
  vi: {
    'nav.home': 'Trang Chủ',
    'nav.partners': 'Đối Tác',
    'nav.academy': 'Học Viện',
    'nav.workspace': 'Ứng Dụng Nbox AI',
    'nav.contact': 'Liên Hệ',
    'nav.getStarted': 'Bắt Đầu',
    'footer.copyright': '© 2026 NBOX AI. HỆ SINH THÁI AI DÀNH CHO KIẾN TRÚC.',
    'footer.privacy': 'Chính Sách Bảo Mật',
    'footer.terms': 'Điều Khoản Dịch Vụ',
    'home.hero.badge': 'Động Cơ Nbox AI V3.0',
    'home.hero.title': 'NBOX AI -\nHỆ SINH THÁI',
    'home.hero.desc': 'Trọn bộ giải pháp giúp hiệu suất công việc của bạn tăng X5 lần. Tái định nghĩa không gian với trí tuệ nhân tạo hiệu suất cao.',
    'home.founder.title': 'NHÀ SÁNG LẬP',
    'home.founder.name': 'TRẦN MINH NHẬT',
    'home.founder.story': 'Kiến trúc sư trưởng của Nbox AI. Người tiên phong trong việc kết nối tính toán thần kinh tiên tiến với thiết kế không gian kiến trúc. Sứ mệnh: Tăng tốc khả năng sáng tạo toàn cầu.',
    'home.founder.slogan': 'KIẾN TẠO THỰC TẠI VỚI TỐC ĐỘ TƯ DUY.',
    'home.cta.ready': 'SẴN SÀNG TÁI CẤU TRÚC?',
    'home.cta.desc': 'Tham gia vào đội tiên phong của cuộc cách mạng kiến trúc. Trải nghiệm tốc độ thiết kế của Nbox AI ngay hôm nay.',
    'home.cta.trial': 'Bắt Đầu Kiến Tạo',
    'home.hero.cta.ignite': 'BẮT ĐẦU KIẾN TẠO',
    'home.hero.cta.demo': 'XEM BẢN DEMO',
    'home.stats.users': 'Nhà Thiết Kế',
    'home.stats.rate': 'Tỉ Lệ Thành Công',
    'home.stats.support': 'Hỗ Trợ Khách Hàng',
    'home.stats.latency': 'Tốc Độ Xử Lý',
    'home.stack.tag': 'Hệ Sinh Thái Kiến Trúc',
    'home.stack.title': 'THIẾT KẾ KHÔNG GIỚI HẠN',
    'home.stack.desc': 'Hệ sinh thái của chúng tôi được thiết kế để tạo ra sản phẩm tốc độ cao, từ bản phác thảo đầu tiên đến kiệt tác cuối cùng.',
    'home.services.1.title': 'Render Ảnh',
    'home.services.1.desc': 'Dựng phối cảnh 3D chân thực từ bản vẽ 2D hoặc hình khối sơ phác.',
    'home.services.2.title': 'AI Render Nội thất',
    'home.services.2.desc': 'Tự động gợi ý phong cách, vật liệu và bố trí nội thất cho không gian sống.',
    'home.services.3.title': 'AI Cải tạo Nhà',
    'home.services.3.desc': 'Gợi ý phương án cải tạo mặt tiền và nội thất dựa trên ảnh hiện trạng.',
    'home.services.4.title': 'AI Render Mặt Bằng',
    'home.services.4.desc': 'Chuyển đổi bản vẽ kỹ thuật CAD thành mặt bằng màu 2D/3D trực quan.',
    'home.services.5.title': 'AI Cảnh quan Sân vườn',
    'home.services.5.desc': 'Thiết kế sân vườn, tiểu cảnh và không gian xanh hài hòa với công trình.',
    'home.services.6.title': 'AI Quy hoạch Đô thị',
    'home.services.6.desc': 'Phân tích và render quy hoạch khu dân cư, đô thị với mật độ tùy chỉnh.',
    'home.services.7.title': 'AI Làm phim Kiến trúc',
    'home.services.7.desc': 'Tạo video diễn họa 3D sống động từ ảnh tĩnh với chuyển động camera mượt mà.',
    'home.services.8.title': 'AI Poster Bất động sản',
    'home.services.8.desc': 'Thiết kế poster quảng cáo bất động sản chuyên nghiệp với sự tối ưu từ AI.',
    'partners.hero.tag': 'Mạng Lưới Chiến Lược',
    'partners.hero.title': 'ĐƯỢC TIN TƯỞNG BỞI CÁC TẬP ĐOÀN THIẾT KẾ TOÀN CẦU',
    'partners.hero.desc': 'Hợp tác với các studio kiến trúc hàng đầu để triển khai các giải pháp render AI tốc độ cao trên toàn thế giới.',
    'partners.deployed.title': 'GIẢI PHÁP ĐÃ TRIỂN KHAI',
    'partners.deployed.desc': 'Các ứng dụng thực tế của Nbox AI trên toàn mạng lưới đối tác toàn cầu.',
    'academy.hero.tag': 'PHÒNG THÍ NGHIỆM THIẾT KẾ NBOX V3.0',
    'academy.hero.title': 'NBOX ACADEMY - KHÓA HỌC AI THỰC CHIẾN',
    'academy.hero.desc': 'Hệ thống các khóa học trực tuyến dành cho kiến trúc sư, diễn họa viên và người làm bất động sản tiếp cận AI thực tế.',
    'academy.course.link': 'LINK KHÓA HỌC',
    'academy.testimonials.title': 'HỌC VIÊN NÓI GÌ VỀ NBOX ACADEMY',
    'academy.faq.title': 'CÂU HỎI THƯỜNG GẶP',
    'academy.detail.back': 'QUAY LẠI',
    'academy.detail.courseDetails': 'CHI TIẾT KHÓA HỌC',
    'academy.detail.for': 'DÀNH CHO',
    'academy.detail.goal': 'MỤC TIÊU',
    'academy.detail.problems': 'VẤN ĐỀ HIỆN TẠI',
    'academy.detail.whatIs': 'LÀ GÌ?',
    'academy.detail.learn': 'BẠN SẼ HỌC GÌ?',
    'academy.detail.outcomes': 'KẾT QUẢ SAU KHÓA HỌC',
    'academy.detail.philosophy': 'TRIẾT LÝ ĐÀO TẠO',
    'academy.detail.register': 'ĐĂNG KÝ NGAY',
    'workspace.title': 'NBOX AI APP',
    'workspace.hero.desc': 'Truy cập các ứng dụng AI chuyên biệt cho kiến trúc hiện đại.',
    'workspace.tabs.catalog': 'CÁC ỨNG DỤNG AI',
    'workspace.tabs.pro': 'CÔNG CỤ AI FLOW',
    'workspace.modal.link': 'Truy Cập Nhanh',
    'workspace.modal.video': 'Video Hướng Dẫn',
    'workspace.modal.tips': 'Mẹo Sử Dụng',
    'contact.hero.tag': 'Kết Nối Với Chúng Tôi',
    'contact.hero.title': 'THAM GIA CUỘC CÁCH MẠNG THIẾT KẾ',
    'contact.hero.desc': 'Liên hệ với đội ngũ Nbox AI để hợp tác kiến trúc, hỗ trợ hoặc các giải pháp doanh nghiệp tùy chỉnh.',
    'contact.journey.title': 'BẮT ĐẦU HÀNH TRÌNH',
    'contact.network.title': 'KẾT NỐI TRỰC TIẾP',
    'contact.social.title': 'HỆ SINH THÁI MẠNG XÃ HỘI',
    'contact.lab.title': 'THAM GIA NBOX AI LAB',
    'contact.lab.desc': 'Trở thành một phần của tương lai kiến trúc. Chúng tôi luôn tìm kiếm những kiến trúc sư đam mê và các nhà nghiên cứu AI.',
    'contact.lab.cta': 'Tham Gia Lab',
    'home.founder_bio.title': 'Trần Minh Nhật là ai?',
    'home.demo.secrets': 'BÍ KÍP AI KIẾN TRÚC',
    'home.demo.action': 'THIẾT KẾ THỰC TẾ',
    'home.demo.tagline': 'Quy trình bứt phá giới hạn thiết kế với sức mạnh từ trí tuệ nhân tạo.',
    'home.demo.try': 'TRẢI NGHIỆM NGAY',
    'academy.available': 'CÁC KHÓA HỌC HIỆN CÓ',
    'academy.training': 'HỆ THỐNG ĐÀO TẠO',
    'services.title': 'DỊCH VỤ AI KIẾN TRÚC & BẤT ĐỘNG SẢN',
    'services.desc': 'Cung cấp các dịch vụ AI chuyên biệt, giúp cá nhân và doanh nghiệp tạo hình ảnh, cải thiện render và sản xuất video dự án nhanh chóng, chất lượng cao.',
    'services.render.title': '1. Dịch vụ Render AI',
    'services.render.subtitle': 'Chỉ với bản sketch tay hoặc ý tưởng ban đầu, NBOX AI giúp bạn tạo phối cảnh trực quan, nhanh chóng.',
    'services.render.f1': 'Tùy chỉnh theo style, tone màu và concept thiết kế',
    'services.render.f2': 'Linh hoạt với nhiều phong cách kiến trúc',
    'services.render.f3': 'Có ngay trong vài giờ',
    'services.render.f4': 'Chất lượng hình ảnh chân thực, ánh sáng và vật liệu tự nhiên',
    'services.improve.title': '2. Dịch vụ cải thiện Render',
    'services.improve.subtitle': 'Ứng dụng AI kết hợp xử lý chuyên sâu giúp hình ảnh trở nên rõ nét, cân bằng ánh sáng và chân thực hơn mà vẫn giữ nguyên ý tưởng thiết kế ban đầu.',
    'services.improve.f1': 'Nâng cấp hình ảnh lên độ phân giải cao (4K Ultra HD)',
    'services.improve.f2': 'Cân bằng ánh sáng, cải thiện vật liệu, tăng độ chân thực',
    'services.improve.f3': 'Đảm bảo giữ nguyên 90% ý tưởng thiết kế gốc',
    'services.improve.f4': 'Xử lý nhanh, phù hợp cả dự án cá nhân và doanh nghiệp',
    'services.video.title': '3. Dịch vụ làm phim AI kiến trúc - bất động sản',
    'services.video.subtitle': 'Giải pháp hiệu quả để trình bày, pitching dự án và quảng bá bất động sản, giúp khách hàng và chủ đầu tư dễ dàng hình dung và đưa ra quyết định.',
    'services.video.f1': 'Chuyển đổi hình ảnh render thành video chuyển động mượt mà',
    'services.video.f2': 'Tăng tính trực quan và cảm xúc khi trình bày dự án',
    'services.video.f3': 'Dễ dàng tùy chỉnh theo yêu cầu nội dung và mục đích sử dụng',
    'services.details.btn': 'XEM CHI TIẾT',
    'services.details.title': 'THÔNG TIN CHI TIẾT',
    'services.details.render.req.title': 'Khách hàng vui lòng cung cấp:',
    'services.details.render.req.1': 'Yêu cầu phân cận cải thiện, chỉnh sửa.',
    'services.details.render.req.2': 'Ảnh có độ phân giải càng cao càng tốt (để giữ đúng chi tiết).',
    'services.details.render.edit.title': 'Khi cần chỉnh sửa:',
    'services.details.render.edit.1': 'Miễn phí chỉnh sửa nhỏ.',
    'services.details.render.edit.2': 'Mỗi lượt chỉnh sửa lớn hoặc làm lại: phí 75%.',
    'services.details.render.price.1': 'Công trình nhỏ (nhà phố, villa)',
    'services.details.render.price.1.val': '200k/hình',
    'services.details.render.price.2': 'Công trình lớn (khách sạn, nhà hàng, chung cư)',
    'services.details.render.price.2.val': '400k/hình',
    'services.details.render.price.3': 'Dự án BĐS',
    'services.details.render.price.3.val': '500k - 1 triệu/hình',
    'services.details.video.price.1': 'Video Công trình nhỏ (1 phút)',
    'services.details.video.price.1.val': '1.5 triệu / video',
    'services.details.video.price.2': 'Video Công trình lớn (1 phút)',
    'services.details.video.price.2.val': '2.5 triệu / video',
    'services.details.video.price.3': 'Video Dự án BĐS (1 phút)',
    'services.details.video.price.3.val': '3.5 triệu / video',
    'services.details.video.req.title': 'Khách hàng vui lòng cung cấp:',
    'services.details.video.req.1': 'Kịch bản.',
    'services.details.video.req.2': 'Hình ảnh kiến trúc.',
    'services.details.video.req.3': 'Một số yêu cầu khác (text, lời thoại, hiệu ứng...).',
    'academy.cta.master': 'SẴN SÀNG LÀM CHỦ AI ĐỈNH CAO?',
    'course.render.details': 'THÔNG TIN CHI TIẾT',
    'academy.card.tools': 'CÔNG CỤ',
    'academy.card.format': 'HÌNH THỨC',
    'academy.card.content': 'NỘI DUNG',
    'partners.custom_app.title': 'GÓI CUSTOM APP DOANH NGHIỆP DÀNH CHO AI?',
    'partners.custom_app.card1.title': 'Bắt kịp xu hướng',
    'partners.custom_app.card1.desc': 'Doanh nghiệp muốn ứng dụng công nghệ AI vào quy trình làm việc',
    'partners.custom_app.card2.title': 'Tăng hiệu suất công việc',
    'partners.custom_app.card2.desc': 'Doanh nghiệp muốn tối ưu hiệu suất công việc, giảm thời gian render',
    'partners.custom_app.card3.title': 'Giao diện WEB riêng biệt',
    'partners.custom_app.card3.desc': 'Doanh nghiệp muốn thể hiện sự chuyên nghiệp, chỉn chu về social network',
    'partners.benefits.title': 'QUYỀN LỢI GÓI APP DOANH NGHIỆP',
    'partners.benefit1': 'Giao diện được custom theo từng công ty',
    'partners.benefit2': 'Tính năng set-up theo nhu cầu sử dụng',
    'partners.benefit3': 'Cho phép nhiều nhân viên truy cập cùng một lúc',
    'partners.benefit4': 'Có group hỗ trợ riêng, phản hồi nhanh',
    'partners.benefit5': 'Cập nhật và bảo hành 10 năm',
    'partners.benefit6': 'Hỗ trợ xuất hóa đơn VAT đầy đủ',
    'partners.pricing.title': 'BẢNG GIÁ CHO 1 APP',
    'partners.pricing.subtitle': '(Phí mua 1 lần - vĩnh viễn)',
    'partners.pricing.credits': 'Credits',
    'partners.pricing.choose': 'Chọn gói này',
    'partners.pricing.pro_badge': 'Phổ biến nhất',
    'partners.pricing.basic': 'Gói Basic',
    'partners.pricing.standard_pkg': 'Gói Standard',
    'partners.pricing.business': 'Gói Business',
    'partners.pricing.enterprise': 'Gói Enterprise',
    'partners.pricing.private': 'Gói Private Plan',
    'partners.pricing.devices.basic': '1–6 thiết bị',
    'partners.pricing.devices.standard': '7–11 thiết bị',
    'partners.pricing.devices.business': '12–16 thiết bị',
    'partners.pricing.devices.enterprise': '17–24 thiết bị',
    'partners.pricing.devices.private': '25 thiết bị trở lên',
    'partners.pricing.negotiable': 'Thương lượng',
    'partners.pricing.feature.speed': 'Tốc độ kết xuất tiêu chuẩn',
    'partners.pricing.feature.support': 'Hỗ trợ ưu tiên 24/7',
    'partners.pricing.feature.early_access': 'Các tính năng truy cập sớm',
    'partners.pricing.ai_service.title': 'DỊCH VỤ AI',
    'partners.pricing.ai_service.subtitle': 'DỊCH VỤ AI KIẾN TRÚC & BẤT ĐỘNG SẢN',
    'partners.pricing.ai_service.desc': 'Cung cấp các dịch vụ AI chuyên biệt, giúp cá nhân và doanh nghiệp tạo hình ảnh, cải thiện render và sản xuất video dự án nhanh chóng, chất lượng cao.',
    'partners.pricing.note': ' Giá chưa bao gồm 8% VAT và phí mua key gateway',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'vi' : 'en');
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
